# Generated by Django 3.1.3 on 2021-02-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210205_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='updated_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
