# Generated by Django 3.1.3 on 2021-02-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
