# Generated by Django 3.1.3 on 2021-02-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210212_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
